### ISSUE TITLE
duplicate jars in alfresco.war

### ISSUE THREAD

**Issue by asmbit** [loftuxab/alfresco-community-loftux#33]
bcmail-jdk15-1.46.jar
bcmail-jdk15on-1.54.jar
bcpkix-jdk15on-1.54.jar
bcprov-jdk15-1.46.jar
bcprov-jdk15on-1.54.jar

**Comment by erny** [comment]
This causes an error when tomcat starts:
```
alfhost_1    | 	Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/alfresco] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1Boolean->org.bouncycastle.asn1.DERBoolean->org.bouncycastle.asn1.ASN1Boolean]
alfhost_1    | 		at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2072)
alfhost_1    | 		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2010)
...
alfhost_1    | 23-Feb-2022 08:47:59.910 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying deployment descriptor [/usr/local/tomcat/conf/Catalina/localhost/alfresco.xml]
alfhost_1    | 	java.lang.IllegalStateException: Error starting child
alfhost_1    | 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
alfhost_1    | 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
...
alfhost_1    | 	Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/alfresco] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1Boolean->org.bouncycastle.asn1.DERBoolean->org.bouncycastle.asn1.ASN1Boolean]
alfhost_1    | 		at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2072)
alfhost_1    | 		at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2010)
```

**Comment by erny** [comment]
Removing bcprov-jdk15-1.46.jar and bcmail-jdk15-1.46.jar fixes this issue.
